name: Deploy Docs to GitHub Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "26.x"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build
        run: npm ci && npm run docs:build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

