name: Publish package to GitHub and NPM Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: "26.x"
      - run: npm ci
      - run: |
          npm run typecheck
          npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: build-result
          path: dist

  publish_gh:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v6
        with:
          node-version: "26.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@tonntr"
          package-manager-cache: false
      - uses: actions/download-artifact@v8
        with:
          name: build-result
          path: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to NPM
      - uses: actions/setup-node@v6
        with:
          node-version: "26.x"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - uses: actions/download-artifact@v8
        with:
          name: build-result
          path: dist
      - run: npm publish --access public
